apiVersion: v1
kind: Service
metadata:
  name: calc-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-deployment
  labels: 
    app: calc-app
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: calc
        image: ravi2krishna/ecomm
        ports:
        - containerPort: 80
