apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-deployment
  labels: 
    app: calc-app
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: tomcat
        image: ravi2krishna/ecomm
        ports:
        - containerPort: 80
