apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: calc-replicaset
  labels: 
    app: calc-app
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: calc
        image: ravi2krishna/ecomm
        ports:
           - containerPort: 80
